input {
  file {
    path => "/usr/share/logstash/logs/app.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb"
  }
}

filter {
  grok {
    match => {
      "message" => '%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} service=%{DATA:service} status=%{NUMBER:status} message="%{GREEDYDATA:log_message}"'
    }
  }

  date {
    match => ["timestamp", "yyyy-MM-dd HH:mm:ss"]
    target => "@timestamp"
  }

  fingerprint {
    source => ["message"]
    target => "[@metadata][fingerprint]"
    method => "SHA256"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "project-logs"
    document_id => "%{[@metadata][fingerprint]}"
  }

  stdout {
    codec => rubydebug
  }
}